// Latency of the requests an editor issues while the user types.
//
// These are guards, not benchmarks: the budgets are deliberately loose so a slow CI runner
// does not fail the build. What they catch is a change in *complexity* - a request that
// starts recompiling the project, or a cache that stops being hit. That failure mode is
// invisible to every other test in this suite, because correctness is unaffected.

import { test, describe, before, after } from 'node:test';
import assert from 'node:assert/strict';

import { LspClient } from './lsp-client.mjs';
import { findServerBinary, stageFiles, locate } from './helpers.mjs';

const FILES = 10;
const DECLS_PER_FILE = 12;

// Absolute ceilings, generous enough that only an order-of-magnitude regression trips them.
// Overridable, because a cold container can be arbitrarily slow.
const WARM_BUDGET_MS = Number(process.env.ARTIC_LSP_WARM_BUDGET_MS ?? 400);
const EDIT_BUDGET_MS = Number(process.env.ARTIC_LSP_EDIT_BUDGET_MS ?? 5000);

// The assertion with teeth: a request answered from the last compile may not recompile, so
// it must land well under the cost of an edit *measured on the same machine, in the same
// run*. The floor keeps it from becoming unfairly tight when a compile happens to be fast.
const warmCeiling = (editRoundTrip) =>
    editRoundTrip === null ? WARM_BUDGET_MS : Math.min(WARM_BUDGET_MS, Math.max(20, editRoundTrip / 2));

const generated = (file) => {
    const lines = ['// Generated by test/latency.test.mjs - not a hand-written fixture.'];
    for (let i = 0; i < DECLS_PER_FILE; i++) {
        const s = `S${file}_${i}`;
        const f = `f${file}_${i}`;
        lines.push(`struct ${s} { a: i32, b: i32 }`);
        lines.push(`fn ${f}(v: ${s}) -> i32 { v.a + v.b }`);
        lines.push(`fn use_${f}(x: i32) -> i32 { ${f}(${s} { a = x, b = x }) }`);
    }
    return lines.join('\n') + '\n';
};

const project = () => {
    const files = {
        'artic.json': JSON.stringify(
            { 'artic-config': '2.0', projects: [{ name: 'latency', files: ['src/*.art'] }] },
            null, 2),
    };
    for (let i = 0; i < FILES; i++) files[`src/gen${i}.art`] = generated(i);
    // One file that reaches into another, so this is a real cross-file project.
    files['src/cross.art'] =
        'fn cross(x: i32) -> i32 { use_f0_0(x) + use_f1_0(x) }\n';
    return files;
};

const median = (xs) => [...xs].sort((a, b) => a - b)[Math.floor(xs.length / 2)];

describe('request latency', () => {
    let ws;
    let client;
    let uri;
    let text;
    let version = 1;
    let editRoundTrip = null;

    // Median wall time of `runs` sequential calls, so one scheduling hiccup cannot fail it.
    const timed = async (t, label, fn, runs = 10) => {
        const samples = [];
        for (let i = 0; i < runs; i++) {
            const start = performance.now();
            await fn(i);
            samples.push(performance.now() - start);
        }
        const mid = median(samples);
        t.diagnostic(`${label}: median ${mid.toFixed(1)}ms, max ${Math.max(...samples).toFixed(1)}ms`);
        return mid;
    };

    before(async () => {
        ws = stageFiles(project());
        client = new LspClient(findServerBinary(), { cwd: ws.dir });
        await client.initialize(ws.uri);

        uri = ws.fileUri('src', 'gen0.art');
        text = ws.read('src', 'gen0.art');
        client.openDocument(uri, text);
        await client.waitForDiagnostics(uri);
    });

    after(async () => {
        await client?.stop();
        ws?.cleanup();
    });

    test('the generated project compiles', () => {
        // Guard: timings taken against a project full of errors would measure the wrong path.
        assert.deepEqual(client.diagnosticsFor(uri).filter((d) => d.severity === 1), []);
    });

    test('an edit is answered with diagnostics promptly', async (t) => {
        editRoundTrip = await timed(t, 'didChange -> publishDiagnostics', async (i) => {
            client.clearDiagnosticsLog();
            client.changeDocument(uri, `${text}\nfn probe${i}() -> i32 { ${i} }\n`, ++version);
            await client.waitForDiagnostics(uri);
        }, 5);
        assert.ok(editRoundTrip < EDIT_BUDGET_MS,
            `edit round trip took ${editRoundTrip.toFixed(1)}ms`);
    });

    test('navigation requests do not recompile', async (t) => {
        // Restore the document so the positions below still hold.
        client.clearDiagnosticsLog();
        client.changeDocument(uri, text, ++version);
        await client.waitForDiagnostics(uri);

        const at = (needle) => locate(text, needle);
        const cases = {
            definition: () => client.request('textDocument/definition',
                { textDocument: { uri }, position: at('f0_0(S0_0') }),
            hover: () => client.request('textDocument/hover',
                { textDocument: { uri }, position: at('f0_0(S0_0') }),
            documentSymbol: () => client.request('textDocument/documentSymbol',
                { textDocument: { uri } }),
            semanticTokens: () => client.request('textDocument/semanticTokens/full',
                { textDocument: { uri } }),
            codeLens: () => client.request('textDocument/codeLens', { textDocument: { uri } }),
            workspaceSymbol: () => client.request('workspace/symbol', { query: 'use_f0' }),
        };

        const ceiling = warmCeiling(editRoundTrip);
        for (const [label, fn] of Object.entries(cases)) {
            const mid = await timed(t, label, fn);
            assert.ok(mid < ceiling,
                `${label} took ${mid.toFixed(1)}ms, ceiling ${ceiling.toFixed(1)}ms`);
        }
    });

    test('completion is answered without a recompile', async (t) => {
        const typed = `${text}\nfn typing() -> i32 {\n    use_f0_\n`;
        client.clearDiagnosticsLog();
        client.changeDocument(uri, typed, ++version);
        await client.waitForDiagnostics(uri);

        const start = locate(typed, '    use_f0_');
        const position = { line: start.line, character: start.character + '    use_f0_'.length };
        const ceiling = warmCeiling(editRoundTrip);
        const mid = await timed(t, 'completion', () =>
            client.request('textDocument/completion', { textDocument: { uri }, position }));
        assert.ok(mid < ceiling,
            `completion took ${mid.toFixed(1)}ms, ceiling ${ceiling.toFixed(1)}ms`);
    });
});
